sendMessageDynamic:
  name: send_message_dynamic
  description: send_message_dynamic from context to an event
#  fields:
#    message:
#      name: "Message"
#      description: "Message"
#      required: false
#      example: "EventSubscription registered"
#      selector:
#        text: